In [148]:
#let us import the different librairies needed for our analysis

import pandas as pd 
import numpy as np

In [149]:
#Let us open the file which is in an excel format 

file = pd.read_excel(r"C:\Users\PCHOME\Desktop\Jasminehelene\Table29.xlsx")

#display of the twelve head rows of our file 

file.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,â€¦ and achieving equality for all women and men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29 Gender empowerment measure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25 Gender empowerment measure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MDG,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,HDI rank,NaN,NaN,Gender empowerment measure \n(GEM),NaN,NaN,NaN,Seats in parliament \nheld by womena,NaN,"Female legislators,\nsenior officials \nand ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
#we need some informations concerning the file we will analyse

file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 33 columns):
Unnamed: 0     206 non-null object
Unnamed: 1     198 non-null object
Unnamed: 2     21 non-null object
Unnamed: 3     199 non-null object
Unnamed: 4     0 non-null float64
Unnamed: 5     178 non-null object
Unnamed: 6     20 non-null float64
Unnamed: 7     200 non-null object
Unnamed: 8     9 non-null object
Unnamed: 9     179 non-null object
Unnamed: 10    26 non-null object
Unnamed: 11    199 non-null object
Unnamed: 12    8 non-null object
Unnamed: 13    191 non-null object
Unnamed: 14    13 non-null object
Unnamed: 15    0 non-null float64
Unnamed: 16    0 non-null float64
Unnamed: 17    0 non-null float64
Unnamed: 18    0 non-null float64
Unnamed: 19    0 non-null float64
Unnamed: 20    0 non-null float64
Unnamed: 21    0 non-null float64
Unnamed: 22    0 non-null float64
Unnamed: 23    0 non-null float64
Unnamed: 24    0 non-null float64
Unnamed: 25    0 non-null float64
Unnamed: 26    0 non-null float64
Unnamed: 27    0 non-null float64
Unnamed: 28    0 non-null float64
Unnamed: 29    0 non-null float64
Unnamed: 30    0 non-null float64
Unnamed: 31    0 non-null float64
Unnamed: 32    0 non-null float64
dtypes: float64(20), object(13)
memory usage: 58.1+ KB

In [151]:
#let us reimport our file because our file header row start from the eleventh row 
 
file = pd.read_excel(r"C:\Users\PCHOME\Desktop\Jasminehelene\Table29.xlsx", header=11)

In [152]:
#let us open the file to verify if our file does start from the eleventh row

file

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,MDG,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,HDI rank,NaN,NaN,Gender empowerment measure \n(GEM),NaN,NaN,NaN,Seats in parliament \nheld by womena,NaN,"Female legislators,\nsenior officials \nand ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Rank,NaN,Value,NaN,(% of total),NaN,(% of total),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Iceland,NaN,5,NaN,0.862,NaN,31.7,NaN,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Norway,NaN,1,NaN,0.910,NaN,37.9,NaN,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3,Australia,NaN,8,NaN,0.847,NaN,28.3,NaN,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4,Canada,NaN,10,NaN,0.820,NaN,24.3,NaN,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5,Ireland,NaN,19,NaN,0.699,NaN,14.2,NaN,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,6,Sweden,NaN,2,NaN,0.906,NaN,47.3,NaN,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7,Switzerland,NaN,27,NaN,0.660,NaN,24.8,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,8,Japan,NaN,54,NaN,0.557,NaN,11.1,NaN,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,9,Netherlands,NaN,6,NaN,0.859,NaN,36.0,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10,France,NaN,18,NaN,0.718,NaN,13.9,NaN,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,11,Finland,NaN,3,NaN,0.887,NaN,42.0,NaN,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,12,United States,NaN,15,NaN,0.762,NaN,16.3,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,13,Spain,NaN,12,NaN,0.794,NaN,30.5,NaN,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,14,Denmark,NaN,4,NaN,0.875,NaN,36.9,NaN,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,15,Austria,NaN,13,NaN,0.788,NaN,31.0,NaN,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,16,United Kingdom,NaN,14,NaN,0.783,NaN,19.3,NaN,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,17,Belgium,NaN,7,NaN,0.850,NaN,35.7,NaN,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,18,Luxembourg,NaN,..,NaN,..,NaN,23.3,NaN,..,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,19,New Zealand,NaN,11,NaN,0.811,NaN,32.2,NaN,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,20,Italy,NaN,21,NaN,0.693,NaN,16.1,NaN,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,21,"Hong Kong, China (SAR)",NaN,..,NaN,..,NaN,..,NaN,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,22,Germany,NaN,9,NaN,0.831,NaN,30.6,NaN,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,23,Israel,NaN,28,NaN,0.660,NaN,14.2,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,24,Greece,NaN,37,NaN,0.622,NaN,13.0,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,25,Singapore,NaN,16,NaN,0.761,NaN,24.5,NaN,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,26,Korea (Republic of),NaN,64,NaN,0.510,NaN,13.4,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,27,Slovenia,NaN,41,NaN,0.611,NaN,10.8,NaN,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,"a. Data are as of 31 May 2007, unless otherwis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,SOURCES\nColumn 1: determined on the basis of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,NaN,GEM ranks for 93 countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,1,Norway,21.0,Italy,NaN,NaN,41.0,Slovenia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,2,Sweden,22.0,Portugal,NaN,NaN,42.0,Bulgaria,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,3,Finland,23.0,Trinidad and Tobago,NaN,NaN,43.0,Ecuador,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,4,Denmark,24.0,Costa Rica,NaN,NaN,44.0,Tanzania (United Republic of),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,5,Iceland,25.0,Lithuania,NaN,NaN,45.0,Philippines,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,6,Netherlands,26.0,Cuba,NaN,NaN,46.0,Mexico,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,7,Belgium,27.0,Switzerland,NaN,NaN,47.0,Honduras,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,8,Australia,28.0,Israel,NaN,NaN,48.0,Cyprus,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,9,Germany,29.0,United Arab Emirates,NaN,NaN,49.0,Panama,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,10,Canada,30.0,Barbados,NaN,NaN,50.0,Hungary,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,11,New Zealand,31.0,Estonia,NaN,NaN,51.0,Mauritius,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,12,Spain,32.0,Peru,NaN,NaN,52.0,Viet Nam,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,13,Austria,33.0,Slovakia,NaN,NaN,53.0,Dominican Republic,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,14,United Kingdom,34.0,Czech Republic,NaN,NaN,54.0,Japan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,15,United States,35.0,Macedonia (TFYR),NaN,NaN,55.0,Moldova,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,16,Singapore,36.0,Namibia,NaN,NaN,56.0,Venezuela (Bolivarian Republic of),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,17,Argentina,37.0,Greece,NaN,NaN,57.0,China,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,18,France,38.0,Latvia,NaN,NaN,58.0,El Salvador,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,19,Ireland,39.0,Poland,NaN,NaN,59.0,Uruguay,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,20,Bahamas,40.0,Croatia,NaN,NaN,60.0,Chile,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
# let us remove from our file all the empty columns and rows , those who are not needed and reset the file 

file = file.dropna(how='all',axis = 0)

file = file.dropna(how='all',axis = 1)

file = file.reset_index(drop=True)

file.head(13)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 5,Unnamed: 6,MDG,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,HDI rank,NaN,NaN,Gender empowerment measure \n(GEM),NaN,NaN,Seats in parliament \nheld by womena,NaN,"Female legislators,\nsenior officials \nand ma...",NaN,Female professional and technical \nworkersb,NaN,Ratio of estimated female to male earned incomec,NaN
1,NaN,NaN,NaN,Rank,Value,NaN,(% of total),NaN,(% of total),NaN,(% of total),NaN,NaN,NaN
2,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Iceland,NaN,5,0.862,NaN,31.7,NaN,27,NaN,56,NaN,0.72,NaN
4,2,Norway,NaN,1,0.910,NaN,37.9,NaN,30,NaN,50,NaN,0.77,NaN
5,3,Australia,NaN,8,0.847,NaN,28.3,NaN,37,NaN,56,NaN,0.70,NaN
6,4,Canada,NaN,10,0.820,NaN,24.3,NaN,36,NaN,56,NaN,0.64,NaN
7,5,Ireland,NaN,19,0.699,NaN,14.2,NaN,31,NaN,52,NaN,0.53,NaN
8,6,Sweden,NaN,2,0.906,NaN,47.3,NaN,30,NaN,51,NaN,0.81,NaN
9,7,Switzerland,NaN,27,0.660,NaN,24.8,NaN,8,NaN,22,NaN,0.63,NaN
10,8,Japan,NaN,54,0.557,NaN,11.1,NaN,10,d,46,d,0.45,NaN
11,9,Netherlands,NaN,6,0.859,NaN,36.0,NaN,26,NaN,50,NaN,0.64,NaN
12,10,France,NaN,18,0.718,NaN,13.9,NaN,37,NaN,47,NaN,0.64,NaN

In [154]:
# let us create columns based on our desired output

columns = []

for col in file.columns:
    
    columns.append([str(s) for s in file[col][:1] if pd.notnull(s)])
    
print(columns)

[['HDI rank'], [], [], ['Gender empowerment measure \n(GEM)'], [], [], ['Seats in parliament \nheld by womena'], [], ['Female legislators,\nsenior officials \nand managersb'], [], ['Female professional and technical \nworkersb'], [], ['Ratio of estimated  female to male earned incomec'], []]

In [155]:
# I am renaming my columns 

columns = ['HDI_rank', 'countries','reference1','GEM_rank','GEM_value','reference_2','seats_parlia_wom','reference3','Fem_le_snr_offi_mana','reference_4','Fem_profes_techn_work','reference_5','Ratio_esti_fem_male_earn_incom','reference_6']


# let us reset the dataframe columns
file.columns = columns


# remove all rows(axis=0) that contains the informations not needed and let us reset the index

file = file.drop(np.arange(2),axis=0).reset_index(drop=True)

file.head()

,HDI_rank,countries,reference1,GEM_rank,GEM_value,reference_2,seats_parlia_wom,reference3,Fem_le_snr_offi_mana,reference_4,Fem_profes_techn_work,reference_5,Ratio_esti_fem_male_earn_incom,reference_6
0,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Iceland,NaN,5,0.862,NaN,31.7,NaN,27,NaN,56,NaN,0.72,NaN
2,2,Norway,NaN,1,0.910,NaN,37.9,NaN,30,NaN,50,NaN,0.77,NaN
3,3,Australia,NaN,8,0.847,NaN,28.3,NaN,37,NaN,56,NaN,0.70,NaN
4,4,Canada,NaN,10,0.820,NaN,24.3,NaN,36,NaN,56,NaN,0.64,NaN

In [156]:
file.tail(120)

,HDI_rank,countries,reference1,GEM_rank,GEM_value,reference_2,seats_parlia_wom,reference3,Fem_le_snr_offi_mana,reference_4,Fem_profes_techn_work,reference_5,Ratio_esti_fem_male_earn_incom,reference_6
84,83,Armenia,NaN,..,..,NaN,9.2,NaN,..,NaN,..,NaN,0.63,NaN
85,84,Turkey,NaN,90,0.298,NaN,4.4,NaN,7,NaN,32,NaN,0.35,NaN
86,85,Suriname,NaN,..,..,NaN,25.5,NaN,..,NaN,..,NaN,0.40,NaN
87,86,Jordan,NaN,..,..,NaN,7.9,NaN,..,NaN,..,NaN,0.31,NaN
88,87,Peru,NaN,32,0.636,NaN,29.2,NaN,34,NaN,46,NaN,0.55,NaN
89,88,Lebanon,NaN,..,..,NaN,4.7,NaN,..,NaN,..,NaN,0.31,NaN
90,89,Ecuador,NaN,43,0.600,NaN,25.0,NaN,35,NaN,48,NaN,0.56,NaN
91,90,Philippines,NaN,45,0.590,NaN,22.1,NaN,58,NaN,61,NaN,0.61,NaN
92,91,Tunisia,NaN,..,..,NaN,19.3,NaN,..,NaN,..,NaN,0.29,NaN
93,92,Fiji,NaN,..,..,NaN,..,h,..,NaN,..,NaN,0.48,NaN
94,93,Saint Vincent and the Grenadines,NaN,..,..,NaN,18.2,NaN,..,NaN,..,NaN,0.51,NaN
95,94,Iran (Islamic Republic of),NaN,87,0.347,NaN,4.1,NaN,16,NaN,34,NaN,0.39,NaN
96,95,Paraguay,NaN,78,0.428,NaN,9.6,NaN,23,NaN,54,d,0.34,NaN
97,96,Georgia,NaN,79,0.414,NaN,9.4,NaN,26,NaN,62,NaN,0.33,NaN
98,97,Guyana,NaN,..,..,NaN,29.0,NaN,..,NaN,..,NaN,0.41,NaN
99,98,Azerbaijan,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.65,NaN
100,99,Sri Lanka,NaN,85,0.369,NaN,4.9,NaN,21,NaN,46,NaN,0.41,NaN
101,100,Maldives,NaN,76,0.437,NaN,12.0,NaN,15,NaN,40,NaN,0.50,NaN
102,101,Jamaica,NaN,..,..,NaN,13.6,NaN,..,NaN,..,NaN,0.56,NaN
103,102,Cape Verde,NaN,..,..,NaN,15.3,NaN,..,NaN,..,NaN,0.35,NaN
104,103,El Salvador,NaN,58,0.529,NaN,16.7,NaN,33,NaN,45,NaN,0.40,NaN
105,104,Algeria,NaN,..,..,NaN,6.2,NaN,..,NaN,32,NaN,0.34,NaN
106,105,Viet Nam,NaN,52,0.561,NaN,25.8,NaN,22,NaN,51,NaN,0.70,NaN
107,106,Occupied Palestinian Territories,NaN,..,..,NaN,..,NaN,11,NaN,35,NaN,..,NaN
108,107,Indonesia,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.46,NaN
109,108,Syrian Arab Republic,NaN,..,..,NaN,12.0,NaN,..,NaN,40,d,0.34,NaN
110,109,Turkmenistan,NaN,..,..,NaN,16.0,NaN,..,NaN,..,NaN,0.64,NaN
111,110,Nicaragua,NaN,..,..,NaN,18.5,NaN,..,NaN,..,NaN,0.32,NaN
112,111,Moldova,NaN,55,0.547,NaN,21.8,NaN,39,NaN,66,NaN,0.63,NaN
113,112,Egypt,NaN,91,0.263,NaN,3.8,NaN,9,NaN,30,NaN,0.23,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,172,Mozambique,NaN,..,..,NaN,34.8,NaN,..,NaN,..,NaN,0.81,NaN
175,173,Mali,NaN,..,..,NaN,10.2,NaN,..,NaN,..,NaN,0.68,NaN
176,174,Niger,NaN,..,..,NaN,12.4,NaN,..,NaN,..,NaN,0.57,NaN
177,175,Guinea-Bissau,NaN,..,..,NaN,14.0,NaN,..,NaN,..,NaN,0.51,NaN
178,176,Burkina Faso,NaN,..,..,NaN,11.7,NaN,..,NaN,..,NaN,0.66,NaN
179,177,Sierra Leone,NaN,..,..,NaN,14.5,NaN,..,NaN,..,NaN,0.45,NaN
180,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,"a. Data are as of 31 May 2007, unless otherwis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,SOURCES\nColumn 1: determined on the basis of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,NaN,GEM ranks for 93 countries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,1,Norway,21.0,Italy,NaN,41.0,Slovenia,NaN,NaN,61,Botswana,NaN,81,Bangladesh
185,2,Sweden,22.0,Portugal,NaN,42.0,Bulgaria,NaN,NaN,62,Belize,NaN,82,Pakistan
186,3,Finland,23.0,Trinidad and Tobago,NaN,43.0,Ecuador,NaN,NaN,63,Malta,NaN,83,Cambodia
187,4,Denmark,24.0,Costa Rica,NaN,44.0,Tanzania (United Republic of),NaN,NaN,64,Korea (Republic of),NaN,84,Qatar
188,5,Iceland,25.0,Lithuania,NaN,45.0,Philippines,NaN,NaN,65,Malaysia,NaN,85,Sri Lanka
189,6,Netherlands,26.0,Cuba,NaN,46.0,Mexico,NaN,NaN,66,Saint Lucia,NaN,86,Nepal
190,7,Belgium,27.0,Switzerland,NaN,47.0,Honduras,NaN,NaN,67,Bolivia,NaN,87,Iran (Islamic Republic of)
191,8,Australia,28.0,Israel,NaN,48.0,Cyprus,NaN,NaN,68,Romania,NaN,88,Morocco
192,9,Germany,29.0,United Arab Emirates,NaN,49.0,Panama,NaN,NaN,69,Colombia,NaN,89,Kyrgyzstan
193,10,Canada,30.0,Barbados,NaN,50.0,Hungary,NaN,NaN,70,Brazil,NaN,90,Turkey
194,11,New Zealand,31.0,Estonia,NaN,51.0,Mauritius,NaN,NaN,71,Russian Federation,NaN,91,Egypt
195,12,Spain,32.0,Peru,NaN,52.0,Viet Nam,NaN,NaN,72,Ethiopia,NaN,92,Saudi Arabia
196,13,Austria,33.0,Slovakia,NaN,53.0,Dominican Republic,NaN,NaN,73,Thailand,NaN,93,Yemen
197,14,United Kingdom,34.0,Czech Republic,NaN,54.0,Japan,NaN,NaN,74,Kazakhstan,NaN,NaN,NaN
198,15,United States,35.0,Macedonia (TFYR),NaN,55.0,Moldova,NaN,NaN,75,Ukraine,NaN,NaN,NaN
199,16,Singapore,36.0,Namibia,NaN,56.0,Venezuela (Bolivarian Republic of),NaN,NaN,76,Maldives,NaN,NaN,NaN
200,17,Argentina,37.0,Greece,NaN,57.0,China,NaN,NaN,77,Mongolia,NaN,NaN,NaN
201,18,France,38.0,Latvia,NaN,58.0,El Salvador,NaN,NaN,78,Paraguay,NaN,NaN,NaN
202,19,Ireland,39.0,Poland,NaN,59.0,Uruguay,NaN,NaN,79,Georgia,NaN,NaN,NaN
203,20,Bahamas,40.0,Croatia,NaN,60.0,Chile,NaN,NaN,80,Oman,NaN,NaN,NaN

In [157]:
# let us drop the rows from the bottom of the data we want 

file = file.drop(np.arange(180,len(file)), axis=0).reset_index(drop=True)

In [158]:
file.tail(90)

,HDI_rank,countries,reference1,GEM_rank,GEM_value,reference_2,seats_parlia_wom,reference3,Fem_le_snr_offi_mana,reference_4,Fem_profes_techn_work,reference_5,Ratio_esti_fem_male_earn_incom,reference_6
90,89,Ecuador,NaN,43,0.600,NaN,25.0,NaN,35,NaN,48,NaN,0.56,NaN
91,90,Philippines,NaN,45,0.590,NaN,22.1,NaN,58,NaN,61,NaN,0.61,NaN
92,91,Tunisia,NaN,..,..,NaN,19.3,NaN,..,NaN,..,NaN,0.29,NaN
93,92,Fiji,NaN,..,..,NaN,..,h,..,NaN,..,NaN,0.48,NaN
94,93,Saint Vincent and the Grenadines,NaN,..,..,NaN,18.2,NaN,..,NaN,..,NaN,0.51,NaN
95,94,Iran (Islamic Republic of),NaN,87,0.347,NaN,4.1,NaN,16,NaN,34,NaN,0.39,NaN
96,95,Paraguay,NaN,78,0.428,NaN,9.6,NaN,23,NaN,54,d,0.34,NaN
97,96,Georgia,NaN,79,0.414,NaN,9.4,NaN,26,NaN,62,NaN,0.33,NaN
98,97,Guyana,NaN,..,..,NaN,29.0,NaN,..,NaN,..,NaN,0.41,NaN
99,98,Azerbaijan,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.65,NaN
100,99,Sri Lanka,NaN,85,0.369,NaN,4.9,NaN,21,NaN,46,NaN,0.41,NaN
101,100,Maldives,NaN,76,0.437,NaN,12.0,NaN,15,NaN,40,NaN,0.50,NaN
102,101,Jamaica,NaN,..,..,NaN,13.6,NaN,..,NaN,..,NaN,0.56,NaN
103,102,Cape Verde,NaN,..,..,NaN,15.3,NaN,..,NaN,..,NaN,0.35,NaN
104,103,El Salvador,NaN,58,0.529,NaN,16.7,NaN,33,NaN,45,NaN,0.40,NaN
105,104,Algeria,NaN,..,..,NaN,6.2,NaN,..,NaN,32,NaN,0.34,NaN
106,105,Viet Nam,NaN,52,0.561,NaN,25.8,NaN,22,NaN,51,NaN,0.70,NaN
107,106,Occupied Palestinian Territories,NaN,..,..,NaN,..,NaN,11,NaN,35,NaN,..,NaN
108,107,Indonesia,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.46,NaN
109,108,Syrian Arab Republic,NaN,..,..,NaN,12.0,NaN,..,NaN,40,d,0.34,NaN
110,109,Turkmenistan,NaN,..,..,NaN,16.0,NaN,..,NaN,..,NaN,0.64,NaN
111,110,Nicaragua,NaN,..,..,NaN,18.5,NaN,..,NaN,..,NaN,0.32,NaN
112,111,Moldova,NaN,55,0.547,NaN,21.8,NaN,39,NaN,66,NaN,0.63,NaN
113,112,Egypt,NaN,91,0.263,NaN,3.8,NaN,9,NaN,30,NaN,0.23,NaN
114,113,Uzbekistan,NaN,..,..,NaN,16.4,NaN,..,NaN,..,NaN,0.60,NaN
115,114,Mongolia,NaN,77,0.429,NaN,6.6,NaN,50,NaN,54,NaN,0.50,NaN
116,115,Honduras,NaN,47,0.589,NaN,23.4,NaN,41,d,52,d,0.46,NaN
117,116,Kyrgyzstan,NaN,89,0.302,NaN,0.0,NaN,25,NaN,57,NaN,0.58,NaN
118,117,Bolivia,NaN,67,0.500,NaN,14.6,NaN,36,NaN,40,NaN,0.57,NaN
119,118,Guatemala,NaN,..,..,NaN,8.2,NaN,..,NaN,..,NaN,0.32,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,149,Djibouti,NaN,..,..,NaN,10.8,NaN,..,NaN,..,NaN,0.48,NaN
151,150,Timor-Leste,NaN,..,..,NaN,25.3,m,..,NaN,..,NaN,..,NaN
152,151,Zimbabwe,NaN,..,..,NaN,22.2,NaN,..,NaN,..,NaN,0.58,NaN
153,152,Togo,NaN,..,..,NaN,8.6,NaN,..,NaN,..,NaN,0.43,NaN
154,153,Yemen,NaN,93,0.129,NaN,0.7,NaN,4,NaN,15,NaN,0.30,NaN
155,154,Uganda,NaN,..,..,NaN,29.8,NaN,..,NaN,..,NaN,0.70,NaN
156,155,Gambia,NaN,..,..,NaN,9.4,NaN,..,NaN,..,NaN,0.53,NaN
157,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,156,Senegal,NaN,..,..,NaN,19.2,NaN,..,NaN,..,NaN,0.54,NaN
159,157,Eritrea,NaN,..,..,NaN,22.0,NaN,..,NaN,..,NaN,0.45,NaN
160,158,Nigeria,NaN,..,..,NaN,..,NaN,..,NaN,..,NaN,0.41,NaN
161,159,Tanzania (United Republic of),NaN,44,0.597,NaN,30.4,NaN,49,NaN,32,NaN,0.73,NaN
162,160,Guinea,NaN,..,..,NaN,19.3,NaN,..,NaN,..,NaN,0.69,NaN
163,161,Rwanda,NaN,..,..,NaN,45.3,NaN,..,NaN,..,NaN,0.74,NaN
164,162,Angola,NaN,..,..,NaN,15.0,NaN,..,NaN,..,NaN,0.62,NaN
165,163,Benin,NaN,..,..,NaN,8.4,NaN,..,NaN,..,NaN,0.47,NaN
166,164,Malawi,NaN,..,..,NaN,13.6,NaN,..,NaN,..,NaN,0.73,NaN
167,165,Zambia,NaN,..,..,NaN,14.6,NaN,..,NaN,..,NaN,0.55,NaN
168,166,CÃ´te d'Ivoire,NaN,..,..,NaN,8.5,NaN,..,NaN,..,NaN,0.32,NaN
169,167,Burundi,NaN,..,..,NaN,31.7,NaN,..,NaN,..,NaN,0.77,NaN
170,168,Congo (Democratic Republic of the),NaN,..,..,NaN,7.7,NaN,..,NaN,..,NaN,0.52,NaN
171,169,Ethiopia,NaN,72,0.477,NaN,21.4,NaN,20,NaN,30,NaN,0.60,NaN
172,170,Chad,NaN,..,..,NaN,6.5,NaN,..,NaN,..,NaN,0.65,NaN
173,171,Central African Republic,NaN,..,..,NaN,10.5,NaN,..,NaN,..,NaN,0.61,NaN
174,172,Mozambique,NaN,..,..,NaN,34.8,NaN,..,NaN,..,NaN,0.81,NaN
175,173,Mali,NaN,..,..,NaN,10.2,NaN,..,NaN,..,NaN,0.68,NaN
176,174,Niger,NaN,..,..,NaN,12.4,NaN,..,NaN,..,NaN,0.57,NaN
177,175,Guinea-Bissau,NaN,..,..,NaN,14.0,NaN,..,NaN,..,NaN,0.51,NaN
178,176,Burkina Faso,NaN,..,..,NaN,11.7,NaN,..,NaN,..,NaN,0.66,NaN
179,177,Sierra Leone,NaN,..,..,NaN,14.5,NaN,..,NaN,..,NaN,0.45,NaN

In [159]:
#let us add remove any row containing the HDI_level list element and put them in a column 

HDI_level_list = ["HIGH HUMAN DEVELOPMENT","MEDIUM HUMAN DEVELOPMENT","LOW HUMAN DEVELOPMENT"]



file = file.drop(file[file["HDI_rank"].isin(HDI_level_list)].index, axis=0).reset_index(drop=True)


#let us add a column to our data for the HDI level

file.loc[:, "HDI_level"] = np.where(file["HDI_rank"] > 155,"LOW HUMAN DEVELOPMENT",np.where(file["HDI_rank"] > 70,"MEDIUM HUMAN DEVELOPMENT","HIGH HUMAN DEVELOPMENT"))


#let us sort our data

file.sort_values(by="HDI_rank", inplace=True)


#let us display the head to see if the column was added

file.head()

,HDI_rank,countries,reference1,GEM_rank,GEM_value,reference_2,seats_parlia_wom,reference3,Fem_le_snr_offi_mana,reference_4,Fem_profes_techn_work,reference_5,Ratio_esti_fem_male_earn_incom,reference_6,HDI_level
0,1,Iceland,NaN,5,0.862,NaN,31.7,NaN,27,NaN,56,NaN,0.72,NaN,HIGH HUMAN DEVELOPMENT
1,2,Norway,NaN,1,0.910,NaN,37.9,NaN,30,NaN,50,NaN,0.77,NaN,HIGH HUMAN DEVELOPMENT
2,3,Australia,NaN,8,0.847,NaN,28.3,NaN,37,NaN,56,NaN,0.70,NaN,HIGH HUMAN DEVELOPMENT
3,4,Canada,NaN,10,0.820,NaN,24.3,NaN,36,NaN,56,NaN,0.64,NaN,HIGH HUMAN DEVELOPMENT
4,5,Ireland,NaN,19,0.699,NaN,14.2,NaN,31,NaN,52,NaN,0.53,NaN,HIGH HUMAN DEVELOPMENT

In [160]:
#let us display our the ninetieth last  rows of our data

file.tail(90)

,HDI_rank,countries,reference1,GEM_rank,GEM_value,reference_2,seats_parlia_wom,reference3,Fem_le_snr_offi_mana,reference_4,Fem_profes_techn_work,reference_5,Ratio_esti_fem_male_earn_incom,reference_6,HDI_level
87,88,Lebanon,NaN,..,..,NaN,4.7,NaN,..,NaN,..,NaN,0.31,NaN,MEDIUM HUMAN DEVELOPMENT
88,89,Ecuador,NaN,43,0.600,NaN,25.0,NaN,35,NaN,48,NaN,0.56,NaN,MEDIUM HUMAN DEVELOPMENT
89,90,Philippines,NaN,45,0.590,NaN,22.1,NaN,58,NaN,61,NaN,0.61,NaN,MEDIUM HUMAN DEVELOPMENT
90,91,Tunisia,NaN,..,..,NaN,19.3,NaN,..,NaN,..,NaN,0.29,NaN,MEDIUM HUMAN DEVELOPMENT
91,92,Fiji,NaN,..,..,NaN,..,h,..,NaN,..,NaN,0.48,NaN,MEDIUM HUMAN DEVELOPMENT
92,93,Saint Vincent and the Grenadines,NaN,..,..,NaN,18.2,NaN,..,NaN,..,NaN,0.51,NaN,MEDIUM HUMAN DEVELOPMENT
93,94,Iran (Islamic Republic of),NaN,87,0.347,NaN,4.1,NaN,16,NaN,34,NaN,0.39,NaN,MEDIUM HUMAN DEVELOPMENT
94,95,Paraguay,NaN,78,0.428,NaN,9.6,NaN,23,NaN,54,d,0.34,NaN,MEDIUM HUMAN DEVELOPMENT
95,96,Georgia,NaN,79,0.414,NaN,9.4,NaN,26,NaN,62,NaN,0.33,NaN,MEDIUM HUMAN DEVELOPMENT
96,97,Guyana,NaN,..,..,NaN,29.0,NaN,..,NaN,..,NaN,0.41,NaN,MEDIUM HUMAN DEVELOPMENT
97,98,Azerbaijan,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.65,NaN,MEDIUM HUMAN DEVELOPMENT
98,99,Sri Lanka,NaN,85,0.369,NaN,4.9,NaN,21,NaN,46,NaN,0.41,NaN,MEDIUM HUMAN DEVELOPMENT
99,100,Maldives,NaN,76,0.437,NaN,12.0,NaN,15,NaN,40,NaN,0.50,NaN,MEDIUM HUMAN DEVELOPMENT
100,101,Jamaica,NaN,..,..,NaN,13.6,NaN,..,NaN,..,NaN,0.56,NaN,MEDIUM HUMAN DEVELOPMENT
101,102,Cape Verde,NaN,..,..,NaN,15.3,NaN,..,NaN,..,NaN,0.35,NaN,MEDIUM HUMAN DEVELOPMENT
102,103,El Salvador,NaN,58,0.529,NaN,16.7,NaN,33,NaN,45,NaN,0.40,NaN,MEDIUM HUMAN DEVELOPMENT
103,104,Algeria,NaN,..,..,NaN,6.2,NaN,..,NaN,32,NaN,0.34,NaN,MEDIUM HUMAN DEVELOPMENT
104,105,Viet Nam,NaN,52,0.561,NaN,25.8,NaN,22,NaN,51,NaN,0.70,NaN,MEDIUM HUMAN DEVELOPMENT
105,106,Occupied Palestinian Territories,NaN,..,..,NaN,..,NaN,11,NaN,35,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
106,107,Indonesia,NaN,..,..,NaN,11.3,NaN,..,NaN,..,NaN,0.46,NaN,MEDIUM HUMAN DEVELOPMENT
107,108,Syrian Arab Republic,NaN,..,..,NaN,12.0,NaN,..,NaN,40,d,0.34,NaN,MEDIUM HUMAN DEVELOPMENT
108,109,Turkmenistan,NaN,..,..,NaN,16.0,NaN,..,NaN,..,NaN,0.64,NaN,MEDIUM HUMAN DEVELOPMENT
109,110,Nicaragua,NaN,..,..,NaN,18.5,NaN,..,NaN,..,NaN,0.32,NaN,MEDIUM HUMAN DEVELOPMENT
110,111,Moldova,NaN,55,0.547,NaN,21.8,NaN,39,NaN,66,NaN,0.63,NaN,MEDIUM HUMAN DEVELOPMENT
111,112,Egypt,NaN,91,0.263,NaN,3.8,NaN,9,NaN,30,NaN,0.23,NaN,MEDIUM HUMAN DEVELOPMENT
112,113,Uzbekistan,NaN,..,..,NaN,16.4,NaN,..,NaN,..,NaN,0.60,NaN,MEDIUM HUMAN DEVELOPMENT
113,114,Mongolia,NaN,77,0.429,NaN,6.6,NaN,50,NaN,54,NaN,0.50,NaN,MEDIUM HUMAN DEVELOPMENT
114,115,Honduras,NaN,47,0.589,NaN,23.4,NaN,41,d,52,d,0.46,NaN,MEDIUM HUMAN DEVELOPMENT
115,116,Kyrgyzstan,NaN,89,0.302,NaN,0.0,NaN,25,NaN,57,NaN,0.58,NaN,MEDIUM HUMAN DEVELOPMENT
116,117,Bolivia,NaN,67,0.500,NaN,14.6,NaN,36,NaN,40,NaN,0.57,NaN,MEDIUM HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,148,Kenya,NaN,..,..,NaN,7.3,NaN,..,NaN,..,NaN,0.83,NaN,MEDIUM HUMAN DEVELOPMENT
148,149,Djibouti,NaN,..,..,NaN,10.8,NaN,..,NaN,..,NaN,0.48,NaN,MEDIUM HUMAN DEVELOPMENT
149,150,Timor-Leste,NaN,..,..,NaN,25.3,m,..,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
150,151,Zimbabwe,NaN,..,..,NaN,22.2,NaN,..,NaN,..,NaN,0.58,NaN,MEDIUM HUMAN DEVELOPMENT
151,152,Togo,NaN,..,..,NaN,8.6,NaN,..,NaN,..,NaN,0.43,NaN,MEDIUM HUMAN DEVELOPMENT
152,153,Yemen,NaN,93,0.129,NaN,0.7,NaN,4,NaN,15,NaN,0.30,NaN,MEDIUM HUMAN DEVELOPMENT
153,154,Uganda,NaN,..,..,NaN,29.8,NaN,..,NaN,..,NaN,0.70,NaN,MEDIUM HUMAN DEVELOPMENT
154,155,Gambia,NaN,..,..,NaN,9.4,NaN,..,NaN,..,NaN,0.53,NaN,MEDIUM HUMAN DEVELOPMENT
155,156,Senegal,NaN,..,..,NaN,19.2,NaN,..,NaN,..,NaN,0.54,NaN,LOW HUMAN DEVELOPMENT
156,157,Eritrea,NaN,..,..,NaN,22.0,NaN,..,NaN,..,NaN,0.45,NaN,LOW HUMAN DEVELOPMENT
157,158,Nigeria,NaN,..,..,NaN,..,NaN,..,NaN,..,NaN,0.41,NaN,LOW HUMAN DEVELOPMENT
158,159,Tanzania (United Republic of),NaN,44,0.597,NaN,30.4,NaN,49,NaN,32,NaN,0.73,NaN,LOW HUMAN DEVELOPMENT
159,160,Guinea,NaN,..,..,NaN,19.3,NaN,..,NaN,..,NaN,0.69,NaN,LOW HUMAN DEVELOPMENT
160,161,Rwanda,NaN,..,..,NaN,45.3,NaN,..,NaN,..,NaN,0.74,NaN,LOW HUMAN DEVELOPMENT
161,162,Angola,NaN,..,..,NaN,15.0,NaN,..,NaN,..,NaN,0.62,NaN,LOW HUMAN DEVELOPMENT
162,163,Benin,NaN,..,..,NaN,8.4,NaN,..,NaN,..,NaN,0.47,NaN,LOW HUMAN DEVELOPMENT
163,164,Malawi,NaN,..,..,NaN,13.6,NaN,..,NaN,..,NaN,0.73,NaN,LOW HUMAN DEVELOPMENT
164,165,Zambia,NaN,..,..,NaN,14.6,NaN,..,NaN,..,NaN,0.55,NaN,LOW HUMAN DEVELOPMENT
165,166,CÃ´te d'Ivoire,NaN,..,..,NaN,8.5,NaN,..,NaN,..,NaN,0.32,NaN,LOW HUMAN DEVELOPMENT
166,167,Burundi,NaN,..,..,NaN,31.7,NaN,..,NaN,..,NaN,0.77,NaN,LOW HUMAN DEVELOPMENT
167,168,Congo (Democratic Republic of the),NaN,..,..,NaN,7.7,NaN,..,NaN,..,NaN,0.52,NaN,LOW HUMAN DEVELOPMENT
168,169,Ethiopia,NaN,72,0.477,NaN,21.4,NaN,20,NaN,30,NaN,0.60,NaN,LOW HUMAN DEVELOPMENT
169,170,Chad,NaN,..,..,NaN,6.5,NaN,..,NaN,..,NaN,0.65,NaN,LOW HUMAN DEVELOPMENT
170,171,Central African Republic,NaN,..,..,NaN,10.5,NaN,..,NaN,..,NaN,0.61,NaN,LOW HUMAN DEVELOPMENT
171,172,Mozambique,NaN,..,..,NaN,34.8,NaN,..,NaN,..,NaN,0.81,NaN,LOW HUMAN DEVELOPMENT
172,173,Mali,NaN,..,..,NaN,10.2,NaN,..,NaN,..,NaN,0.68,NaN,LOW HUMAN DEVELOPMENT
173,174,Niger,NaN,..,..,NaN,12.4,NaN,..,NaN,..,NaN,0.57,NaN,LOW HUMAN DEVELOPMENT
174,175,Guinea-Bissau,NaN,..,..,NaN,14.0,NaN,..,NaN,..,NaN,0.51,NaN,LOW HUMAN DEVELOPMENT
175,176,Burkina Faso,NaN,..,..,NaN,11.7,NaN,..,NaN,..,NaN,0.66,NaN,LOW HUMAN DEVELOPMENT
176,177,Sierra Leone,NaN,..,..,NaN,14.5,NaN,..,NaN,..,NaN,0.45,NaN,LOW HUMAN DEVELOPMENT

In [166]:
# let us convert our file to a csv format


file.to_csv(r"C:\Users\PCHOME\Desktop\Nouveau dossier.csv", index=False)